[tool.poetry]
name = "dingtalk-robot"
version = "0.1.0"
description = ""
authors = ["Yezhou <yezhou@lightedpath.local>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.11.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
